name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test --stacktrace

  dokka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: regenerate documentation
        run: |
          rm -rf docs
          ./gradlew dokkahtml
          mv app/build.dokka/html ./docs
      - name: Commit changes
        run: |
          git add -f docs
          git diff-index --quiet HEAD || git commit -m "Auto update"
          - name: push documentation
          run: git push -u origin master
